name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get Version
      id: get_version
      run: echo "VERSION=$(node -p "require('./module.json').version")" >> $GITHUB_ENV

    # Wechselt direkt in das Verzeichnis und zippt nur die nackten Dateien auf Root-Ebene
    - name: Zip Files
      run: |
        zip -r ./json-uploader.zip module.json main.js
        # Falls du Styles oder andere Ordner hättest, würden sie hier dazukommen

    - name: Update Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./module.json
          ./json-uploader.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}