name: Release Creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get Version
      id: get_version
      run: echo "VERSION=$(node -p "require('./module.json').version")" >> $GITHUB_ENV

    # Packt ALLES im Ordner ein, schließt aber Git und die Workflows selbst aus
    # Dadurch landen module.json und main.js GARANTIERT zusammen im ZIP
    name: Create Perfect Zip
      run: |
        zip -r ./module.zip . -x "*.git*" ".github*"

    - name: Create and Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          ./module.json
          ./module.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}