name: Release Creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Nutzt ein offizielles GitHub-Tool zum sauberen Zippen ohne versteckte Unterordner
    - name: Missing Files Fix (Zip)
      uses: theunites/zip-action@v2.2.0
      with:
        files: |
          module.json
          main.js
        dest: ./json-uploader.zip

    - name: Create and Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          ./module.json
          ./json-uploader.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}